// ---------------------------------------------------------------------------
// Shared types for the OCI ingestion service
// ---------------------------------------------------------------------------

export interface FeedConfig {
  url: string;
  beat: string;
}

export interface ParsedRssItem {
  title: string;
  link: string;
  description: string;
  guid?: string;
  pubDate?: string;
}

export interface CandidateCluster {
  titleHash: string;
  leadTitle: string;
  normalizedTitle: string;
  alternateHeadlines: string[];
  outletNames: string[];
  outletCount: number;
  beat: string;
  language: string;
  country: string;
  publishedAt?: number;
  // Receipt fields
  feedUrl: string;
  googleNewsUrl: string;
  rssGuid?: string;
  rssPublishedAt?: number;
  rssTitle: string;
  rssDescriptionText?: string;
  retrievedAt: number;
}

export interface StoryBundle {
  leadTitle: string;
  alternateHeadlines: string[];
  outletNames: string[];
  googleNewsUrl: string;
  beats: string[];
}

export interface HermesSource {
  sourceName: string;
  url: string;
  accessed: boolean;
  accessedAt: string;
  notes: string;
  content: string;
  contentKind: "article_text" | "snippet" | "search_result" | "rss_description" | "other";
  confidence: number;
}

export interface HermesResponse {
  summaryBullets: string[];
  whyItMatters: string;
  suggestedBeat: string;
  confidence: number;
  missingContext: string[];
  sources: HermesSource[];
}

export interface HermesCallResult {
  status: "success" | "timeout" | "parse_error" | "failed";
  latencyMs: number;
  httpStatus?: number;
  response?: HermesResponse;
  usage?: {
    prompt_tokens?: number;
    completion_tokens?: number;
    total_tokens?: number;
  };
  error?: string;
}

export interface CostEstimate {
  inputTokens: number;
  outputTokens: number;
  totalTokens: number;
  usageSource: "provider" | "estimated" | "none";
  estimatedCostCents: number;
}

export type FeedFetchOutcome =
  | {
      status: "ok";
      feed: FeedConfig;
      httpCode: number;
      byteCount: number;
      latencyMs: number;
      itemCount: number;
      candidates: CandidateCluster[];
    }
  | {
      status: "error";
      feed: FeedConfig;
      error: string;
      errorClass: string;
      latencyMs: number;
      httpCode?: number;
    };

export interface IngestionRunAggregate {
  feedsSucceeded: number;
  feedsFailed: number;
  itemsSeen: number;
  clustersCreated: number;
  clustersUpdated: number;
  duplicatesSkipped: number;
}

// ---------------------------------------------------------------------------
// Newsroom organisation types (ONR-004)
// ---------------------------------------------------------------------------

/** A single specialist role derived by the Editor-in-Chief. */
export interface RoleSpec {
  /** Unique role id, e.g. "markets-reporter", "tech-analyst" */
  roleId: string;
  /** Human-readable name, e.g. "Markets Reporter" */
  name: string;
  /** Why this role exists for this edition */
  rationale: string;
  /** Which story cluster IDs are assigned to this role */
  assignedClusterIds: string[];
  /** The mission statement for this worker */
  mission: string;
  /** Allowed tool categories */
  allowedTools: string[];
  /** Explicit guardrails */
  guardrails: string[];
  /** How to know this role succeeded */
  successCriteria: string[];
  /** Parent trace — reference back to the editorial plan */
  parentTrace: string;
  /** Token budget for this role (soft limit) */
  tokenBudget: number;
  /** Time budget in ms for this role */
  timeBudgetMs: number;
  /** Whether this role was explicitly named in manager instructions */
  wasNamed: boolean;
}

/** The editorial plan generated by the Editor-in-Chief. */
export interface EditorialPlan {
  /** Plan id (edition key or similar) */
  planId: string;
  /** Edition key this plan is for */
  editionKey: string;
  /** Top-level editorial direction */
  editorialDirection: string;
  /** Sections to produce */
  sections: Array<{
    name: string;
    description: string;
    priority: number;
  }>;
  /** Derived role specs */
  roles: RoleSpec[];
  /** Beats that were detected but deliberately not spawned */
  dormantBeats: string[];
  /** Rationale for why dormant beats were excluded */
  dormantRationale: string;
  /** Total token budget for this edition */
  totalTokenBudget: number;
  /** Concurrency limit for workers */
  concurrencyLimit: number;
  /** Timestamp when plan was created */
  createdAt: number;
  /** Input summary — what candidates and context went in */
  inputDigest: string;
}

/** Structured output from a single worker. */
export interface WorkerResult {
  /** Which role produced this */
  roleId: string;
  /** Unique result id */
  resultId: string;
  /** The edition key */
  editionKey: string;
  /** The story this worker produced */
  story: {
    title: string;
    summary: string;
    summaryBullets: string[];
    beat: string;
    confidence: number;
    sources: Array<{
      url: string;
      name: string;
      accessed: boolean;
    }>;
  };
  /** Worker self-assessment */
  selfAssessment: {
    meetsCriteria: boolean;
    reasoning: string;
  };
  /** Raw Hermes response for audit */
  rawResponse: string;
  /** Whether this result passed schema validation */
  validationStatus: "valid" | "invalid" | "repaired";
  /** Any validation errors */
  validationErrors: string[];
  /** Whether a repair was attempted */
  repairAttempted: boolean;
  /** Repair attempt detail if applicable */
  repairDetail?: string;
  /** Cost */
  tokensUsed: number;
  estimatedCostCents: number;
  latencyMs: number;
}

/** Revision note from the manager back to a worker. */
export interface RevisionNote {
  /** Which role to revise */
  roleId: string;
  /** What specifically is wrong */
  concerns: string[];
  /** Concrete suggestions for improvement */
  suggestions: string[];
  /** Whether this is a required or optional revision */
  severity: "required" | "optional";
}

/** A single revision loop: reject → revise → accept/reject. */
export interface RevisionLoop {
  loopId: string;
  editionKey: string;
  roleId: string;
  /** The original result that was rejected */
  originalResultId: string;
  /** The revision note sent to the worker */
  revisionNote: RevisionNote;
  /** The revised result (if worker produced one) */
  revisedResultId?: string;
  /** Final disposition */
  disposition: "accepted" | "rejected" | "pending";
  /** Round number (0 = initial, 1 = first revision) */
  round: number;
  createdAt: number;
}

/** A persisted lesson or successful role pattern. */
export interface NewsroomMemory {
  memoryId: string;
  /** What kind of memory */
  kind: "lesson" | "role_pattern" | "editorial_rule" | "guardrail";
  /** The lesson content */
  content: string;
  /** Tags for retrieval */
  tags: string[];
  /** Provenance — which edition or run produced this */
  provenance: string;
  /** Confidence in this lesson */
  confidence: number;
  createdAt: number;
}

// ---------------------------------------------------------------------------
// Judge types (ONR-005)
// ---------------------------------------------------------------------------

/** A single atomic claim extracted from a script line. */
export interface JudgeClaim {
  claimId: string;
  editionKey: string;
  claim: string;
  storyKey: string;
  roleId: string;
  sourceLines: string[];
}

/** Evidence from a single source. */
export interface EvidenceReceipt {
  url: string;
  name: string;
  accessed: boolean;
  excerpt?: string;
  linkupUsed: boolean;
  linkupResultCount?: number;
}

export type ClaimVerdict = "approved" | "revise" | "block" | "escalate";

export interface ClaimVerdictResult {
  claimId: string;
  verdict: ClaimVerdict;
  reason: string;
  evidence: EvidenceReceipt[];
  receiptsCorroborated: boolean;
  linkupCorroborated: boolean;
  conflictDetail?: string;
  confidence: number;
  tokensUsed: number;
  estimatedCostCents: number;
  latencyMs: number;
}

export interface JudgeResult {
  editionKey: string;
  verdicts: ClaimVerdictResult[];
  approved: number;
  blocked: number;
  revised: number;
  escalated: number;
  totalTokensUsed: number;
  totalCostCents: number;
  totalLatencyMs: number;
}

// ---------------------------------------------------------------------------
// Audio pipeline types (ONR-006)
// ---------------------------------------------------------------------------

export interface AnchorTurn {
  anchor: "A" | "B";
  text: string;
  pronunciation?: string;
  isChapterStart: boolean;
  storyKey?: string;
}

export interface AudioScript {
  editionKey: string;
  language: "en" | "hi";
  turns: AnchorTurn[];
  wordCount: number;
  chapterMap: Record<string, number>;
}

export interface AudioSegment {
  segmentId: string;
  editionKey: string;
  anchor: "A" | "B";
  turnIndex: number;
  text: string;
  voiceId: string;
  durationMs: number;
  clipUrl: string;
  costCents: number;
  latencyMs: number;
  createdAt: number;
}

export interface EditionAudio {
  editionKey: string;
  totalDurationMs: number;
  fullAudioUrl: string;
  chapters: Array<{ storyKey: string; startMs: number; title: string }>;
  segments: AudioSegment[];
  totalCostCents: number;
  totalLatencyMs: number;
}
